let seedSites = [
  {
  img: "http://divebums.com/wrecks/images/NOSC-Tower/diver-NOSC-Tower_2008_jen-tople.jpg",
  date: "06/20/18",
  city: "San Diego, CA",
  country: "USA",
  name: "NOSC Tower",
  buddies: ["Nathan", "Feelix"],
  weather: "Sunny, 80°",
  diveTime: "1 hr 10 min",
  airConsumption: 1500,
  maxDepth: 80,
  wildlife: ['Tube anenome', 'mantis shrimp', 'nudibranch', 'eel'],
  additionalComments: 'cool dive, visibility not amazing',
  rating: 6
},
{
img: "https://media-cdn.tripadvisor.com/media/photo-s/09/43/ce/f8/la-jolla-dive.jpg",
date: "08/03/17",
city: "San Diego, CA",
country: "USA",
name: "La Jolla Canyon",
buddies: ["Breanne", "Vivian"],
weather: "Choppy waves, 75°",
diveTime: "1 hr 30 min",
airConsumption: 1700,
maxDepth: 90,
wildlife: "Bat Rays, Guitar Fish, Bait Fish",
additionalComments: "Swim directly out from the Lifeguard Station #20. To conserve air, you may want to surface swim for a little over 100yds before descending (just past a white buoy). At about 40’, the bottom begins to drop off in a series of ledges and walls that stair step downward to depths beyond recreational diving limits.",
rating: 8
},
{
img: "https://www.californiabeaches.com/wp-content/uploads/2014/09/IMG_2272-Large-933x700.jpg",
date: "05/18/16",
city: "Monterey, CA",
country: "USA",
name: "McAbee Beach",
buddies: ["Patty", "Kelly"],
weather: "Overcast, 72°",
diveTime: "56 min",
airConsumption: 1200,
maxDepth: 50,
wildlife: 'Rays, seals',
additionalComments: "This is a great first dive in Monterey. The depths are shallow with about 50' maximum. The waves are usually smaller than at other locations and the entry is easy.",
rating: 7
},
{
img: "http://www.theperfectdive.com/media/photos/396.jpg",
date: "07/12/18",
city: "Carmel, CA",
country: "USA",
name: "Monestery, South",
buddies: ["Jasmine", "Sean"],
weather: "Sunny, 83°",
diveTime: "45 min",
airConsumption: 1200,
maxDepth: 50,
wildlife: "Leopard Sharks, Lobster",
additionalComments: "Large granite reef structures and giant kelp forests offer endless exploration opportunities to divers. CAUTION: Surf entry and exit experience required. The site has become infamous for its difficult shore entry conditions that periodically claim the lives of divers.",
rating: 6
},
{
img: "http://www.theperfectdive.com/media/photos/912.jpg",
date: "06/25/16",
city: "Palos Verdes Peninsula, CA",
country: "USA",
name: "Abalone Cove",
buddies: ["Emily", "Pat"],
weather: "Medium visibility, 70°",
diveTime: "1 hr 20 min",
airConsumption: 1600,
maxDepth: 50,
wildlife: "Nudibranches, Shrimp",
additionalComments: "Large kelp beds mark the submerged reef particularly on the west side of the cove. There may also be some cool scenery on the left side of the cove at the point below the cliffs around the wash rocks.",
rating: 6
},
{
img: "https://scubadiverlife.com/wp-content/uploads/2016/04/Undercut-at-Coco-View-1024x768.jpg",
date: "07/07/18",
city: "Roatan",
country: "Honduras",
name: "Coco View Wall",
buddies: ["Pat", "Walt", "Nate"],
weather: "Sunny, 88°",
diveTime: "1 hr 27 min",
airConsumption: 1600,
maxDepth: 82,
wildlife: "seahorses, lobsters, crab, garden eels",
additionalComments: "One of my favorite south shore wall dives is CoCo View Wall, which is located within swimming distance of CoCo View Resort, but is open to all divers. It plunges down about 82 feet (25 m) from the surface and is heavily encrusted with soft and hard corals.",
rating: 10
},
{
img: "https://i1.wp.com/scubadiverlife.com/wp-content/uploads/2016/04/Coral-Canyon-at-Marys-Place2.jpg?zoom=2&w=446&h=335&crop&ssl=1",
date: "07/07/18",
city: "Roatan",
country: "Honduras",
name: "Mary's Place",
buddies: ["Pat", "Walt", "Nate"],
weather: "Sunny, 85°",
diveTime: "1 hr 20 min",
airConsumption: 1400,
maxDepth: 70,
wildlife: "Soft Coral, Tuna",
additionalComments: "Many consider this the best dive on the island, and it’s a great one to be sure — a series of deep coral canyons, teeming with macro life. But while it definitely makes my top five, it’s not No. 1, simply because of the crowds. Every diver has heard about Mary’s Place, which means it can feel like there’s a lineup of dive groups waiting to splash in.",
rating: 9
},
{
img: "https://i1.wp.com/scubadiverlife.com/wp-content/uploads/2016/04/Inside-Dolphins-Den.jpg?zoom=2&w=427&h=320&crop&ssl=1",
date: "07/08/18",
city: "Roatan",
country: "Honduras",
name: "Dolphin's Den",
buddies: ["Rachel", "Sheryl", "Lisa"],
weather: "Overcast, 80°",
diveTime: "1 hr 10 min",
airConsumption: 1400,
maxDepth: 70,
wildlife: "Nurse sharks, anemones, snapping shrimp",
additionalComments: "Dolphin’s Den is thusly named because deep within one of the tunnels is the skull of a dolphin. Our divemaster suggested the poor creature may have swum in, become disoriented and drowned.",
rating: 9
},
{
img: "https://i0.wp.com/scubadiverlife.com/wp-content/uploads/2016/04/Nudibranch-at-Fish-Den.jpg?zoom=2&w=598&h=448&crop&ssl=1",
date: "07/08/18",
city: "Roatan",
country: "Honduras",
name: "Fish Den",
buddies: ["Nate", "Sabrina", "Rachel"],
weather: "Overcast, 80°",
diveTime: "1 hr 35 min",
airConsumption: 1600,
maxDepth: 65,
wildlife: "Sea turtles, gobies, angelfish",
additionalComments: " If you’re an underwater photographer, this site is a must. With great light penetration and shallow depths, photographers can take their time finding and composing shots.",
rating: 8
},
{
img: "https://i2.wp.com/scubadiverlife.com/wp-content/uploads/2016/04/El-Aguila2.jpg?zoom=2&w=446&h=335&crop&ssl=1",
date: "07/09/18",
city: "Roatan",
country: "Honduras",
name: "El Aguila",
buddies: ["Vivian", "Breanne", "Patty"],
weather: "Sunny/Overcast, 79°",
diveTime: 55,
airConsumption: 1400,
maxDepth: 50,
wildlife: "Huge Groupers, green moray eels, barracuda",
additionalComments: "If you dive Roatan, the El Aguila is a must-do.",
rating: 8
}

];

module.exports = seedSites;
