let seedSites = [
  {
  img: "http://divebums.com/wrecks/images/NOSC-Tower/diver-NOSC-Tower_2008_jen-tople.jpg",
  date: "06/20/18",
  location: "San Diego, CA",
  name: "NOSC Tower",
  buddies: ["Nathan", "Feelix"],
  weather: "Sunny, 80°",
  diveTime: "1 hr 10 min",
  airConsumption: 1500,
  maxDepth: 80,
  wildlife: ['Tube anenome', 'mantis shrimp', 'nudibranch', 'eel'],
  additionalComments: 'cool dive, visibility not amazing',
  rating: 6
},
{
img: String,
date: Date,
location: String,
name: String,
buddies: [String],
weather: String,
diveTime: Number,
airConsumption: Number,
maxDepth: Number,
wildlife: String,
additionalComments: String,
rating: {type: Number, min: 0, max: 10}
},
{
img: String,
date: Date,
location: String,
name: String,
buddies: [String],
weather: String,
diveTime: Number,
airConsumption: Number,
maxDepth: Number,
wildlife: String,
additionalComments: String,
rating: {type: Number, min: 0, max: 10}
},
{
date: Date,
location: String,
name: String,
buddies: [String],
weather: String,
diveTime: Number,
airConsumption: Number,
maxDepth: Number,
wildlife: String,
additionalComments: String,
rating: {type: Number, min: 0, max: 10}
},
{
img: String,
date: Date,
location: String,
name: String,
buddies: [String],
weather: String,
diveTime: Number,
airConsumption: Number,
maxDepth: Number,
wildlife: String,
additionalComments: String,
rating: {type: Number, min: 0, max: 10}
},
{
img: String,
date: Date,
location: String,
name: String,
buddies: [String],
weather: String,
diveTime: Number,
airConsumption: Number,
maxDepth: Number,
wildlife: String,
additionalComments: String,
rating: {type: Number, min: 0, max: 10}
},
{
img: String,
date: Date,
location: String,
name: String,
buddies: [String],
weather: String,
diveTime: Number,
airConsumption: Number,
maxDepth: Number,
wildlife: String,
additionalComments: String,
rating: {type: Number, min: 0, max: 10}
},
{
img: String,
date: Date,
location: String,
name: String,
buddies: [String],
weather: String,
diveTime: Number,
airConsumption: Number,
maxDepth: Number,
wildlife: String,
additionalComments: String,
rating: {type: Number, min: 0, max: 10}
},
{
img: String,
date: Date,
location: String,
name: String,
buddies: [String],
weather: String,
diveTime: Number,
airConsumption: Number,
maxDepth: Number,
wildlife: String,
additionalComments: String,
rating: {type: Number, min: 0, max: 10}
},
{
img: String,
date: String,
location: String,
name: String,
buddies: [String],
weather: String,
diveTime: Number,
airConsumption: Number,
maxDepth: Number,
wildlife: String,
additionalComments: String,
rating: {type: Number, min: 0, max: 10}
}

];

module.exports = seedSites;
